name: CI/CD Pipeline for FastAPI Banking App

# Trigger the workflow on push and pull_request events to the main branch
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Test job
  test:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python environment
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: |
          pytest # Ensure you have some tests, e.g., in `tests/` folder

  # Build & Deploy job (if tests pass)
  build_deploy:
    runs-on: ubuntu-latest
    needs: test  # Ensure tests pass before building/deploying
    if: success()

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: |
          docker build -t my-fastapi-bank-app .

      - name: Log in to Docker Hub (optional)
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub (optional)
        run: |
          docker tag my-fastapi-bank-app ${{ secrets.DOCKER_USERNAME }}/my-fastapi-bank-app:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/my-fastapi-bank-app:latest

      - name: Deploy to Server (optional, with SSH or other methods)
        run: |
          # For example, if deploying to a remote server using SSH
          ssh user@your-server "docker pull ${{ secrets.DOCKER_USERNAME }}/my-fastapi-bank-app:latest && docker run -d -p 8000:8000 my-fastapi-bank-app"
